src/Entity/Property.php
<?php

namespace App\Entity;

use App\Repository\PropertyRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\DateTimeType;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\HttpFoundation\File\File ;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Vich\UploaderBundle\Mapping\Annotation as Vich;



/**
 * @ORM\Entity(repositoryClass=PropertyRepository::class)
 * @Vich\Uploadable()
 */
class Property
{

    const ASSURANCE = [
        0 => "acunne",
        1 => "une année "

    ];
    




    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string|null
     * @ORM\Column(type="string", length=255)
     */
    private $filename;


    /**
     * @var File|null
     * @Vich\UploadableField(mapping="property_image",fileNameProperty="filename")
     */
    private $imageFile;








    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;


    /**
     * @var string
     * 
     * @Gedmo\Slug(fields={"title"})
     * 
     * @ORM\Column(type="string", length=255,nullable=false)
     */
    private $slug;





    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     */
    private $nbplaces;

    /**
     * @ORM\Column(type="integer")
     */
    private $nbportes;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $couleur;

    /**
     * @ORM\Column(type="integer")
     */
    private $nbchevaux;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     */
    private $assurance;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $marque;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $origin;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $serie;

    /**
     * @ORM\Column(type="boolean", options={"default": false })
     */
    private $sold = false ;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\ManyToMany(targetEntity=Option::class, inversedBy="properties")
     */
    private $options;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;


    public function __construct()
    {
        $this->created_at = new \DateTime();
        $this->options = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

   

    public function getSlug(): string
    {
        return $this-> slug;
    }

    public function setSlug(string $slug): self
    {
         $this->slug = $slug;
         return $this;
    }



    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getNbplaces(): ?int
    {
        return $this->nbplaces;
    }

    public function setNbplaces(int $nbplaces): self
    {
        $this->nbplaces = $nbplaces;

        return $this;
    }

    public function getNbportes(): ?int
    {
        return $this->nbportes;
    }

    public function setNbportes(int $nbportes): self
    {
        $this->nbportes = $nbportes;

        return $this;
    }

    public function getCouleur(): ?string
    {
        return $this->couleur;
    }

    public function setCouleur(string $couleur): self
    {
        $this->couleur = $couleur;

        return $this;
    }

    public function getNbchevaux(): ?int
    {
        return $this->nbchevaux;
    }

    public function setNbchevaux(int $nbchevaux): self
    {
        $this->nbchevaux = $nbchevaux;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getFormattedPrice(): string
    {
        return number_format($this->price,0,'',' ');
    }

    public function getAssurance(): ?int
    {
        return $this->assurance;
    }

    public function setAssurance(int $assurance): self
    {
        $this->assurance = $assurance;

        return $this;
    }


    public function getAssuranceType(): string
    {
        return self::ASSURANCE[$this->assurance];

        
    }

    public function getMarque(): ?string
    {
        return $this->marque;
    }

    public function setMarque(string $marque): self
    {
        $this->marque = $marque;

        return $this;
    }

    public function getOrigin(): ?string
    {
        return $this->origin;
    }

    public function setOrigin(string $origin): self
    {
        $this->origin = $origin;

        return $this;
    }

    public function getSerie(): ?string
    {
        return $this->serie;
    }

    public function setSerie(string $serie): self
    {
        $this->serie = $serie;

        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getCreatedAt(): ?\DateTime
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTime $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return Collection|Option[]
     */
    public function getOptions(): Collection
    {
        return $this->options;
    }

    public function addOption(Option $option): self
    {
        if (!$this->options->contains($option)) {
            $this->options[] = $option;
            $option->addProperty($this);
        }

        return $this;
    }

    public function removeOption(Option $option): self
    {
        if ($this->options->removeElement($option)) {
            $option->removeProperty($this);
        }

        return $this;
    }


    /**
     * @return null|string
     */
    public function getFilename(): ?string
    {
        return $this->filename;
    }

    /**
     * @param null|string $filename
     * @return Property
     */

    public function setFilename(?string $filename): Property
    {
        $this->filename =$filename;
        return $this;
    }



    
    /**
     * @return null|File
     */
    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    /**
     * @param null|File $imageFile
     * @return Property
     */

    public function setImageFile(?File $imageFile): Property
    {
        $this->imageFile =$imageFile;

        if ($this->imageFile instanceof UploadedFile){
            $this->updated_at = new \DateTime('now');
        }
        return $this;
    }

    public function getUpdatedAt(): ?\DateTime
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTime $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }






}

src/Form/PropertyType.php
<?php

namespace App\Form;

use App\Entity\Option;
use App\Entity\Property;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;

use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PropertyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('nbplaces')
            ->add('nbportes')
            ->add('couleur')
            ->add('nbchevaux')
            ->add('price')
            ->add('assurance', ChoiceType::class,[
                'choices' => $this->getChoices()
            ])
            ->add('options',EntityType::class,[
                'class' => Option::class,
                'choice_label' => 'name',
                'multiple' => true
            ])
            ->add('imageFile', FileType::class, [
                'required' => true
            ])
            ->add('marque')
            ->add('origin')
            ->add('serie')
            ->add('sold')
            
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Property::class,
        ]);
    }

    private function getChoices()
    {
        $choices = Property::ASSURANCE;
        $output = [];
        foreach($choices as $k => $v){
            $output[$v] = $k;
        }
        return $output;
    }




}


    

src/Controller/PropertyController.php
<?php

namespace App\Controller;

use App\Entity\Property;
use App\Entity\PropertySearch;
use App\Form\PropertySearchType;
use App\Repository\PropertyRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route; 
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class PropertyController extends AbstractController
{


    /**
     * @var PropertyRepository
     */
    private $repository;

    public function __construct(PropertyRepository $repository)
    {
        $this-> repository = $repository;
       
    }





    /**
     *@Route("/biens",name="property.index")
     *@return Response     
     */
    public function index(PaginatorInterface $paginator,Request $request): Response 
    {
        $search = new PropertySearch();
        $form = $this-> createForm( PropertySearchType::class, $search);
        $form -> handleRequest($request);
        $properties  = $paginator->paginate(
            $this->repository->findAllVisibleQuery($search),
            $request->query->getInt('page', 1), 
            4 
        );
       

        $em = $this->getDoctrine()->getManager();
        
    
        return $this->render('property/index.html.twig',[
            'current_menu' => 'properties',
            'properties' => $properties,
            'form'       => $form->createView()
        ]);
    }



     /**
     *@Route("/biens/{title}-{id}",name="property.show")
     *@return Response     
     */
    public function show(Property $property): Response 
    {

        
        
        
    
        return $this->render('property/show.html.twig',[
            'property' => $property,
            'current_menu' => 'properties'
        ]);
    }


   

}

templates/property/_property.html.twig
    <div class="col-3 mb-4">
    {% if property.filename %}
        <img src="/images/properties/{{ property.filename }}" alt="card-img-top" style="width:100%; ">
    {% endif %}

        <div class="card">
            <div class="card-body">
                <h5 class="card-title">
                    <a href="{{ path('property.show',{id: property.id, title: property.title})}}"> {{ property.title }} </a>
                </h5>
                    <p class="card-text" > {{property.nbchevaux}} cv -   {{property.origin}} ({{property.marque}})  </p>
                <div class="text-primary" style="font-weight:bold; font-size: 2rem;" > {{property.formattedPrice }} DT </div>
            </div>
        </div>
    </div>

  






    

templates/property/index.html.twig
{%extends 'base.html.twig'%}

{%block title 'Tous nos bien' %}

{%block body%}

<div class="jumbotron">

    <div class="container mt-4 mb-4 align-items">

    {{ form_start(form) }}
    <div class="form-row">
        <div class="col">
             {{ form_row(form.maxPrice)}}
        </div>
        <div class="col">
            {{ form_row(form.minNbChevaux)}}
        </div>
        <div class="col">
            {{ form_row(form.options)}}
        </div>
        <div class="col">
            <button class="btn btn-primary">Rechercher</button>
        </div>
    </div>
    {{ form_end(form) }}

    

    </div>

</div>


<div class="container">
<div class=" mt-4 mb-4 ">
<h1>voir tous nos bien</h1>

<div class="row">
    {% for property in properties %}
        {% include 'property/_property.html.twig'  %}
    {% endfor %}
</div>

<div class="pagination">
    
        {{ knp_pagination_render(properties)}}
    
</div>


</div>



</div>

{%endblock%}

templates/property/show.html.twig
{%extends 'base.html.twig'%}

{%block title property.title %}

{%block body%}

<div class="jumbotron">

    <div class="container">
        <div class="row">
            <div class="col-md-8">
                {% if property.filename %}
                     <img src="/images/properties/{{ property.filename }}" alt="card-img-top" style="width:100%; ">
                {% endif %}
            </div>
            <div class="col-md-4">
                <h1>{{property.title}}</h1>
                <h3>{{property.nbplaces}} places - {{property.nbportes}} portes</h3>
                <div class="text-primary" style="font-size: 3rem; font-weight: bold;" >{{property.formattedPrice}} DT </div>
                <a href="#" class="btn btn-primary">Contacter l'agence</a>
            </div>
        </div>

        
    </div>

</div>






<div class="container mt-4">


    <p> 
               {{property.description | nl2br}}
    </p>
   


    <div class="row">
        <div class="col-md-8">
            <h2>Caractéristiques</h2>

           <table class="table table-striped">

                <tr>
                    <td>chevaux</td>
                    <td>{{property.nbchevaux}} ch </td>
                </tr>
                <tr>
                    <td>places</td>
                    <td>{{property.nbplaces}} places </td>
                </tr>
                <tr>
                    <td>portes</td>
                    <td>{{property.nbportes}} portes </td>
                </tr>
                <tr>
                    <td>couleur</td>
                    <td>{{property.couleur}}  </td>
                </tr>
                <tr>
                    <td>assurance</td>
                    <td>{{property.assuranceType}}  </td>
                </tr>

            </table>

        </div>

        <div class="col-md-4">
            
            <h2>Spécificités</h2>
            <ul class="list-group" >
            {% for option in property.options %}
                <li class="list-group-item">{{ option.name}}</li>
            {% endfor %} 

            
        </div>
       
    </div>









</div>




{%endblock%}